# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/kulanidu/flyrank_ML/blob/main/work/notebooks/w03_data_contract.ipynb)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [36]:
from google.colab import userdata

HF_TOKEN = userdata.get("HF_TOKEN").strip()

In [37]:
from datasets import load_dataset

ds = load_dataset(
    "FlyRank/internship-warehouse",
    "dim_clients",
    streaming=True,
    token=HF_TOKEN
)

first = next(iter(ds["train"]))
print(first)

{'client_hash_id': 'client_04660893ae39614a', 'is_active': True, 'has_gsc_access': True, 'has_ga4_access': True, 'access_profile': 'gsc_and_ga4', 'client_created_date': datetime.date(2026, 4, 15), 'client_updated_date': datetime.date(2026, 6, 27), 'gsc_data_start': None, 'ga4_data_start': datetime.date(2026, 5, 22)}

In [38]:
from datasets import load_dataset

tables = [
    "dim_clients",
    "dim_content",
    "fact_content_daily_performance",
    "fact_content_query_90d"
]

for table in tables:
    ds = load_dataset(
        "FlyRank/internship-warehouse",
        table,
        streaming=True,
        token=HF_TOKEN
    )

    first = next(iter(ds["train"]))

    print("=" * 70)
    print(table)
    print("Columns:")
    print(list(first.keys()))

======================================================================
dim_clients
Columns:
['client_hash_id', 'is_active', 'has_gsc_access', 'has_ga4_access', 'access_profile', 'client_created_date', 'client_updated_date', 'gsc_data_start', 'ga4_data_start']
======================================================================
dim_content
Columns:
['client_hash_id', 'content_hash_id', 'keyword_hash_id', 'url_hash_id', 'keyword_char_count', 'keyword_token_count', 'url_char_count', 'content_created_date', 'content_updated_date', 'content_type', 'search_volume', 'competition', 'competition_level', 'cpc', 'main_intent', 'backlinks', 'category_count', 'keyword_created_date', 'provider_used', 'model_used', 'char_count', 'word_count', 'last_optimized_date', 'optimization_eligible_date', 'is_published', 'is_deleted']

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

======================================================================
fact_content_daily_performance
Columns:
['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events']
======================================================================
fact_content_query_90d
Columns:
['client_hash_id', 'content_hash_id', 'query_hash_id', 'query_char_count', 'query_token_count', 'window_start', 'window_end', 'impressions_90d', 'clicks_90d', 'impressions_last30', 'clicks_last30', 'impressions_prev30', 'clicks_prev30', 'avg_position_90d', 'avg_position_last30', 'avg_position_prev30', 'content_total_impressions_90d', 'content_visible_query_count', 'rare_query_count', 'rare_impressions_share', 'anonymized_impressions_share']

In [39]:
from datasets import load_dataset
import pandas as pd

ds = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_daily_performance",
    streaming=True,
    token=HF_TOKEN
)

sample = list(ds["train"].take(5))
df = pd.DataFrame(sample)

print("Shape:", df.shape)
display(df)

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Shape: (5, 30)

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_paid,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events
0,2025-01-27,client_9958f0a7ae1df715,content_3b70a18ea133b2bb,True,True,True,False,30,0,115,...,0,0,0,0,0,0,0,0,0,0
1,2025-01-27,client_9958f0a7ae1df715,content_fe8e8155ce1d47a2,True,True,True,False,5,0,358,...,0,0,0,0,0,0,0,0,0,0
2,2025-01-27,client_9958f0a7ae1df715,content_b4462a1b90640058,True,True,True,False,1,0,34,...,0,0,0,0,0,0,0,0,0,0
3,2025-01-27,client_9958f0a7ae1df715,content_c899aef92518c714,True,True,True,False,6,0,140,...,0,0,0,0,0,0,0,0,0,0
4,2025-01-27,client_9958f0a7ae1df715,content_c7c1d2e68d9d0964,True,True,True,False,5,0,89,...,0,0,0,0,0,0,0,0,0,0

In [40]:
print(df[["report_date", "client_hash_id", "content_hash_id"]])

  report_date           client_hash_id           content_hash_id
0  2025-01-27  client_9958f0a7ae1df715  content_3b70a18ea133b2bb
1  2025-01-27  client_9958f0a7ae1df715  content_fe8e8155ce1d47a2
2  2025-01-27  client_9958f0a7ae1df715  content_b4462a1b90640058
3  2025-01-27  client_9958f0a7ae1df715  content_c899aef92518c714
4  2025-01-27  client_9958f0a7ae1df715  content_c7c1d2e68d9d0964

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

In [41]:
from IPython.display import Markdown, display

display(Markdown("""
# Unit of Analysis + Time Window

**Unit of analysis:** One row represents the daily performance of one content item for one client on one report date.

**Time window:** This lane uses daily observations from the `fact_content_daily_performance` table. Each record belongs to a single report date and allows content performance to be analyzed over time.
"""))

# Unit of Analysis + Time Window

**Unit of analysis:** One row represents the daily performance of one content item for one client on one report date.

**Time window:** This lane uses daily observations from the `fact_content_daily_performance` table. Each record belongs to a single report date and allows content performance to be analyzed over time.

In [42]:
print("Dataset shape:", df.shape)

print("\nUnit of analysis columns:")
display(df[["report_date", "client_hash_id", "content_hash_id"]])

Dataset shape: (5, 30)

Unit of analysis columns:

  report_date           client_hash_id           content_hash_id
0  2025-01-27  client_9958f0a7ae1df715  content_3b70a18ea133b2bb
1  2025-01-27  client_9958f0a7ae1df715  content_fe8e8155ce1d47a2
2  2025-01-27  client_9958f0a7ae1df715  content_b4462a1b90640058
3  2025-01-27  client_9958f0a7ae1df715  content_c899aef92518c714
4  2025-01-27  client_9958f0a7ae1df715  content_c7c1d2e68d9d0964

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

In [43]:
for col in df.columns:
    print(col)

report_date
client_hash_id
content_hash_id
client_has_gsc
client_has_ga4
gsc_data_available
ga4_data_available
gsc_impressions
gsc_clicks
gsc_sum_position
gsc_avg_position
ga4_pageviews
ga4_sessions
ga4_users
ga4_engaged_sessions
ga4_total_engagement_sec
sessions_organic
sessions_direct
sessions_referral
sessions_social
sessions_paid
sessions_ai
ai_chatgpt
ai_perplexity
ai_gemini
ai_copilot
ai_claude
ai_meta
ai_other
scroll_events

In [44]:
from IPython.display import Markdown, display

display(Markdown("""
# Fields: Feature / Label / Context / Excluded

## Features
- gsc_impressions
- gsc_clicks
- gsc_sum_position
- gsc_avg_position
- ga4_pageviews
- ga4_sessions
- ga4_users
- ga4_engaged_sessions
- ga4_total_engagement_sec
- sessions_organic
- sessions_direct
- sessions_referral
- sessions_social
- sessions_paid
- sessions_ai
- ai_chatgpt
- ai_perplexity
- ai_gemini
- ai_copilot
- ai_claude
- ai_meta
- ai_other
- scroll_events

These are measurable search, engagement, traffic and AI referral signals that may help explain content performance.

## Label
No final prediction label has been defined yet.
A target variable will be created later depending on the selected modeling lane.

## Context
- report_date
- client_hash_id
- content_hash_id
- client_has_gsc
- client_has_ga4
- gsc_data_available
- ga4_data_available

These identify the client, content item, report date and data availability but are not direct predictive features.

## Excluded
No columns are excluded at this stage.
Identifiers and availability fields are treated as context rather than predictive features.
"""))

# Fields: Feature / Label / Context / Excluded

## Features
- gsc_impressions
- gsc_clicks
- gsc_sum_position
- gsc_avg_position
- ga4_pageviews
- ga4_sessions
- ga4_users
- ga4_engaged_sessions
- ga4_total_engagement_sec
- sessions_organic
- sessions_direct
- sessions_referral
- sessions_social
- sessions_paid
- sessions_ai
- ai_chatgpt
- ai_perplexity
- ai_gemini
- ai_copilot
- ai_claude
- ai_meta
- ai_other
- scroll_events

These are measurable search, engagement, traffic and AI referral signals that may help explain content performance.

## Label
No final prediction label has been defined yet.
A target variable will be created later depending on the selected modeling lane.

## Context
- report_date
- client_hash_id
- content_hash_id
- client_has_gsc
- client_has_ga4
- gsc_data_available
- ga4_data_available

These identify the client, content item, report date and data availability but are not direct predictive features.

## Excluded
No columns are excluded at this stage.
Identifiers and availability fields are treated as context rather than predictive features.

In [45]:
print("Features:", 23)
print("Context:", 7)
print("Excluded:", 0)

Features: 23
Context: 7
Excluded: 0

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

In [46]:
print("Checking the unit of analysis...\n")

display(df[[
    "report_date",
    "client_hash_id",
    "content_hash_id"
]].head())

print("\nEach row represents:")
print("- one report date")
print("- one client")
print("- one content item")

Checking the unit of analysis...

  report_date           client_hash_id           content_hash_id
0  2025-01-27  client_9958f0a7ae1df715  content_3b70a18ea133b2bb
1  2025-01-27  client_9958f0a7ae1df715  content_fe8e8155ce1d47a2
2  2025-01-27  client_9958f0a7ae1df715  content_b4462a1b90640058
3  2025-01-27  client_9958f0a7ae1df715  content_c899aef92518c714
4  2025-01-27  client_9958f0a7ae1df715  content_c7c1d2e68d9d0964

Each row represents:
- one report date
- one client
- one content item

In [47]:
from datasets import load_dataset

ds = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_daily_performance",
    streaming=True,
    token=HF_TOKEN
)

count = 0
for _ in ds["train"].take(1000):
    count += 1

print("Verified first", count, "rows can be streamed successfully.")

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Verified first 1000 rows can be streamed successfully.

In [48]:
sample = list(ds["train"].take(100))
df = pd.DataFrame(sample)

missing = df.isnull().sum()

display(missing)

report_date                 0
client_hash_id              0
content_hash_id             0
client_has_gsc              0
client_has_ga4              0
gsc_data_available          0
ga4_data_available          0
gsc_impressions             0
gsc_clicks                  0
gsc_sum_position            0
gsc_avg_position            0
ga4_pageviews               0
ga4_sessions                0
ga4_users                   0
ga4_engaged_sessions        0
ga4_total_engagement_sec    0
sessions_organic            0
sessions_direct             0
sessions_referral           0
sessions_social             0
sessions_paid               0
sessions_ai                 0
ai_chatgpt                  0
ai_perplexity               0
ai_gemini                   0
ai_copilot                  0
ai_claude                   0
ai_meta                     0
ai_other                    0
scroll_events               0
dtype: int64

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

In [49]:
from IPython.display import Markdown, display

display(Markdown("""
# Data Limits

This dataset has several important limitations that should be considered during analysis.

- The dataset contains anonymized client and content identifiers, so individual clients or websites cannot be identified.
- Client history is unbalanced, meaning different clients have different amounts of historical data.
- Some early records may contain only Google Search Console (GSC) information or only Google Analytics 4 (GA4) information.
- The dataset represents observational search performance data and cannot establish causal relationships.
- Future labels must be created carefully to avoid data leakage during model training.
"""))

# Data Limits

This dataset has several important limitations that should be considered during analysis.

- The dataset contains anonymized client and content identifiers, so individual clients or websites cannot be identified.
- Client history is unbalanced, meaning different clients have different amounts of historical data.
- Some early records may contain only Google Search Console (GSC) information or only Google Analytics 4 (GA4) information.
- The dataset represents observational search performance data and cannot establish causal relationships.
- Future labels must be created carefully to avoid data leakage during model training.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.